DEFAULT_CONFIG: dict = {
    "version": "1.1",
    "vault_path": "",
    "google_api_key": "",
    "gemma_model": "gemma-4-31b-it",
    "temperature": 0.2,
    "max_tokens": 8192,
    "chunk_seconds": 6,
    "chunk_overlap": 0.5,
    "inference_device": "auto",
    "auto_open_obsidian": False,
    "prevent_sleep": True,
    "show_waveform": True,
    "record_shortcut": "Cmd+R",
    "include_frontmatter": True,
    "frontmatter_tags": "[{course_lower}, lecture, notes]",
    "custom_prompt_suffix": "",
    "note_language": "English",
    "courses": [],
    "pending_update": None,  # {"version": "vX.Y.Z", "url": "..."}
}
